version: "3"

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    user: user
    entrypoint: php
    working_dir: /home/user/app
    volumes:
      - .:/home/user/app

  composer:
    build:
      context: .
      dockerfile: Dockerfile
    user: user
    entrypoint: composer
    working_dir: /home/php/app
    volumes:
      - .:/home/php/app

  artisan:
    build:
      context: .
      dockerfile: Dockerfile
    user: user
    entrypoint: php artisan
    working_dir: /home/php/app
    volumes:
      - .:/home/php/app

  nginx:
    depends_on:
      - fpm
    container_name: nginx
    build:
      context: nginx
      dockerfile: Dockerfile
    command: nginx
    ports:
      - 80:80
    volumes:
      - .:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d/www.conf:/etc/nginx/conf.d/www.conf

  fpm:
    depends_on:
      - postgresql
    container_name: fpm
    build:
      context: .
      dockerfile: Dockerfile
    command: php-fpm7 --nodaemonize
    volumes:
      - .:/usr/share/nginx/html
      - ./fpm/php-fpm.d/www.conf:/etc/php7/php-fpm.d/www.conf

  postgresql:
    container_name: postgresql
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_USER: $DB_USERNAME
      POSTGRES_DB: $DB_DATABASE
    volumes:
      - ./postgres/data:/var/lib/postgresql/data

  adminer:
    image: adminer
    ports:
      - 8080:8080

